apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azuredevops-provider-chart.fullname" . }}
  labels:
    {{- include "azuredevops-provider-chart.labels" . | nindent 4 }}
data:
  AZURE_DEVOPS_PROVIDER_DEBUG: "{{ .Values.env.AZURE_DEVOPS_PROVIDER_DEBUG }}"
  AZURE_DEVOPS_PROVIDER_POLL_INTERVAL: {{ .Values.env.AZURE_DEVOPS_PROVIDER_POLL_INTERVAL }}
