apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "azuredevops-provider-chart.fullname" . }}
  labels:
    {{- include "azuredevops-provider-chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccount: {{ include "azuredevops-provider-chart.fullname" . }}-job-sa
      containers:
        - name: {{ include "azuredevops-provider-chart.fullname" . }}-patcher
          image: bitnami/kubectl
          command: ['/bin/bash','/tmp/mount/create-certs.sh', {{ .Release.Namespace }},  {{ include "azuredevops-provider-chart.fullname" . }}]
          volumeMounts:
            - name: script-volume
              mountPath: /tmp/mount
      volumes:
        - name: script-volume
          configMap:
            name: {{ include "azuredevops-provider-chart.fullname" . }}-script-configmap
