apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "azuredevops-provider.fullname" . }}-apply-job
  labels:
    {{- include "azuredevops-provider.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccount: {{ include "azuredevops-provider.fullname" . }}-job-sa
      containers:
        - name: {{ include "azuredevops-provider.fullname" . }}-kubectl
          image: bitnami/kubectl
          command:
            - kubectl
            - patch
            - crd
            - pipelinepermissions.azuredevops.krateo.io
            - --patch-file
            - /tmp/{{ include "azuredevops-provider.fullname" . }}-crd.yaml
          volumeMounts:
            - name: crd-volume
              mountPath: /tmp
      volumes:
        - name: crd-volume
          configMap:
            name: {{ include "azuredevops-provider.fullname" . }}-configmap
