apiVersion: azuredevops.krateo.io/v1alpha1
kind: Feed
metadata:
  name: feed-sample-3
spec:
  deletionPolicy: Orphan
  projectRef:
    namespace: default
    name: teamproject
  upstreamSources:
    - name: upstream-prova
      protocol: npm
      upstreamSourceType: internal
      location: azure-feed://matteogastaldello/pipelineProj/feed-prova@Local
    - name: upstream-prova
      protocol: pypi
      upstreamSourceType: internal
      location: azure-feed://matteogastaldello/pipelineProj/feed-prova@Local
    - name: upstream-feed
      protocol: npm
      upstreamSourceType: internal
      location: azure-feed://matteogastaldello/teamproject/TestFeed@Local
    - name: upstream-feed
      protocol: maven
      upstreamSourceType: internal
      location: azure-feed://matteogastaldello/teamproject/TestFeed@Local
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
