apiVersion: azuredevops.krateo.io/v1alpha2
kind: PipelinePermission
metadata:
  name: pipelinepermission-v2-var
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  deletionPolicy: Orphan
  authorizeAll: false
  projectRef: 
    name: pipeline-proj
    namespace: default
  pipelines:
    - pipelineRef:
        name: pipeline-sample
        namespace: default
      authorized: false
    - pipelineRef:
        name: pipeline-sample-2
        namespace: default
      authorized: false
  resource:
    type: variablegroup # other possible value are: repository;environment;queue;teamproject;endpoint;variablegroup;securefile
    resourceRef:
      name: vg-test-1
      namespace: default
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
