apiVersion: azuredevops.krateo.io/v1alpha1
kind: PipelinePermission
metadata:
  name: pipelinepermission-sample
spec:
  organization: krateo-kog
  project: 99837031-4e4e-4753-9a47-73fcc4cba766
  authorize: true
  resource:
    type: repository
    id: 5605b0ba-e2fa-4aab-af0b-0888321b3a08
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
