apiVersion: azuredevops.krateo.io/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-sample
spec:
  name: test-pipeline-helloworld
  folder: test-folder
  configurationType: yaml
  definitionPath: azure-pipelines-helloworld.yaml
  repositoryType: azureReposGit
  repositoryRef:
    name: gitrepository-sample
    namespace: default
  projectRef:
    name: teamproject-sample
    namespace: default
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
