apiVersion: azuredevops.krateo.io/v1alpha1
kind: Users
metadata:
  name: user-build
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  deletionPolicy: Delete
  organization: matteogastaldello
  user:
    name: teamproject Build Service (matteogastaldello)
  groupRefs:
    - namespace: default
      name: group-sample
    - namespace: default
      name: group-test
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
